/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.lang.*;
import java.util.*;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.*;
import chatroom.*;

/**
 *
 * @author eecamp
 */
public class ChatRoomHall extends javax.swing.JPanel {

    /**
     * Creates new form ChatRoomHall
     */

    private Client client;
    // msgTextPane elements
    private StyledDocument inputDoc;    
    private StyledDocument dialogDoc;
    private String inputText;
    private String dialogText;
    private boolean whisper;
    public int roomKey;

    // guestList elements;
    private Vector<String> userList;    // all users who connect to server
    
    public ChatRoomHall(Client c) {
        initComponents();
        roomKey = 0;
        client = c;
        inputDoc = inputTextPane.getStyledDocument();
        dialogDoc = dialogTextPane.getStyledDocument();
        inputText = new String();
        dialogText = new String();              // empty string
        userList = new Vector<String>();        // get list form server!!    
        userListPanel.setListData(userList);
        whisper = false;
    }

    java.util.List<Element> getAllElements(JTextPane x) {
	Element[] roots = x.getStyledDocument().getRootElements();
	return getAllElements(roots);
    }
    
    private java.util.List<Element> getAllElements(Element[] roots) {
        java.util.List<Element> icons = new LinkedList<Element>();
        for (int a = 0; a < roots.length; a++) {
            if(roots[a] == null)
                continue ;
            icons.add(roots[a]);
            for (int c = 0; c < roots[a].getElementCount(); c++) {
                Element element = roots[a].getElement(c);
                icons.addAll(getAllElements(new Element[] { element }));
            }
        }
        return icons;
    }
    
    public String getInputText(JTextPane x) {
        Map<Integer,String> mp = new HashMap<Integer,String>();
        String t =x.getText();
        java.util.List<Element> els = getAllElements(x);
        for(Element el : els) {
            Icon icon = StyleConstants.getIcon(el.getAttributes());
            if(icon != null) {
                String tmp = ((ImageIcon)icon).getDescription();
                // 假设 icon中的desc存放它的 filePath
                mp.put(el.getStartOffset(), tmp);
            }
        }
        StringBuffer tt = new StringBuffer("");
        char[] chr = t.toCharArray();
        for(int c=0; c<chr.length; c++) {
            String v = mp.get(new Integer(c));
            if(v == null) {
                tt.append("\002p\003");
                tt.append(chr[c]);
            }
            else {
                tt.append("\002m\003");
                tt.append(v);
            }
        }
        return tt.toString();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        dialogTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        userListPanel = new javax.swing.JList();
        sendToCombo = new javax.swing.JComboBox();
        cryButton = new javax.swing.JButton();

        inputTextPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTextPaneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTextPaneKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(inputTextPane);

        jScrollPane2.setViewportView(dialogTextPane);

        userListPanel.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        userListPanel.setToolTipText("");
        jScrollPane3.setViewportView(userListPanel);

        sendToCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"To All"}));
        sendToCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToComboActionPerformed(evt);
            }
        });

        cryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/cry.png"))); // NOI18N
        cryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(sendToCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sendToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputTextPaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextPaneKeyPressed
        // TODO add your handling code here:
        String s = (String) sendToCombo.getSelectedItem() ;
        if(!s.equals("To All")){ 
            whisper = true;
        }
        else{
            whisper = false;
        }
        // for test
        if(evt.getKeyChar( )== '\n'&& client.getLogState()){
          //  client.send(parseInputText(inputTextPane.getText()));
//            inputText = inputTextPane.getText();
            inputText = getInputText(inputTextPane);
            refreshInputPane();
            System.out.println(inputText);
            if(!inputText.equals("") ){
                showMessage();
                if(!whisper){
                    client.sendRoomMsg(roomKey,inputText);
                }else{
                    String receiver = (String)sendToCombo.getSelectedItem();
                    client.sendWhisper(roomKey,receiver,inputText);
                }
            }
        }
    }//GEN-LAST:event_inputTextPaneKeyPressed

    private void inputTextPaneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextPaneKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyChar() == '\n' ){
            inputTextPane.setText("");
        }
    }//GEN-LAST:event_inputTextPaneKeyReleased

    private void sendToComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToComboActionPerformed
        // TODO add your handling code here:
        // should change color of user
    }//GEN-LAST:event_sendToComboActionPerformed

    private void cryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cryButtonActionPerformed
        // TODO add your handling code here:
        inputTextPane.setCaretPosition(inputDoc.getLength());
        ImageIcon icon = new ImageIcon("image/cry.png");
        inputTextPane.insertIcon(icon);
        
        System.out.println(icon.getDescription());
    }//GEN-LAST:event_cryButtonActionPerformed
    private String parseInputText(String str){
        StringBuffer msgBuffer = new StringBuffer(""); // must create a empty buffer first
        char[] strCharArray = str.toCharArray();
        for(int i = 0; i < str.length(); ++i){ 
            msgBuffer.append(strCharArray[i]);
        }
        return msgBuffer.toString();
    }
    
    private void refreshInputPane () {
        try {
            inputDoc.insertString( inputDoc.getLength(),
                              inputTextPane.getText(),
                              null );
        }
        catch (BadLocationException ble) {
            System.err.println("Couldn't insert initial text into text pane.");
        }
        inputTextPane.setText("");
    }
    private void showMessage(){
        try {
            String[] tokens = inputText.split("\002");
            String newText;
            if(whisper){
                String receiver = (String)sendToCombo.getSelectedItem();
                newText = "\n" + "( TO "+ receiver + " )"+client.username + " :";// + inputText;
            }
            else{
                newText = "\n" + client.username + " :";// + inputText;
            }
            dialogTextPane.setCaretPosition(dialogTextPane.getStyledDocument().getLength());
            dialogTextPane.getStyledDocument().insertString(dialogTextPane.getCaretPosition(), newText, null);
        
            for (String token : tokens) {
                if (token.length() == 0) continue;
            
                String[] subTokens = token.split("\003");
                String type = subTokens[0];
                System.out.println(type);
                String content = subTokens[1];
                System.out.println(content);
            //StyledDocument doc = dialogTextPane.getStyledDocument();
                
                dialogTextPane.setCaretPosition(dialogTextPane.getStyledDocument().getLength());
                if (type.equals("m")) {
                    //doc.insertString(doc.getLength(), content, null);
                    dialogTextPane.getStyledDocument().insertString(dialogTextPane.getCaretPosition(), content, null);
                }
                else if (type.equals("p")) {
                    dialogTextPane.insertIcon(new ImageIcon(content));
                }
                else {
                    System.out.println("WRONG MESSAGE QQQQQQQQQQQQQQQQQQQQ");
                }
            }
        }
        catch (BadLocationException ex) {
            System.out.println("BAD LOCATION QQQQQQQQQQQQQQQQQQQQ");
        }
    }
    
    public void showRecvMessage(String sender, String msg, boolean whisper_recv){
        try {
            String newText;
            String[] tokens = msg.split("\002");
            if(whisper_recv){
                newText = "\n" + "( FROM "+ sender+ " )" + " :";// + msg;
            }
            else{
                newText = "\n" + sender + " :";// + msg;
            }
            dialogTextPane.setCaretPosition(dialogTextPane.getStyledDocument().getLength());
            dialogTextPane.getStyledDocument().insertString(dialogTextPane.getCaretPosition(), newText, null);
        
            for (String token : tokens) {
                if (token.length() == 0) continue;
            
                String[] subTokens = token.split("\003");
                String type = subTokens[0];
                System.out.println(type);
                String content = subTokens[1];
                System.out.println(content);
            //StyledDocument doc = dialogTextPane.getStyledDocument();
                
                dialogTextPane.setCaretPosition(dialogTextPane.getStyledDocument().getLength());
                if (type.equals("m")) {
                    //doc.insertString(doc.getLength(), content, null);
                    dialogTextPane.getStyledDocument().insertString(dialogTextPane.getCaretPosition(), content, null);
                }
                else if (type.equals("p")) {
                    dialogTextPane.insertIcon(new ImageIcon(content));
                }
                else {
                    System.out.println("WRONG MESSAGE QQQQQQQQQQQQQQQQQQQQ");
                }
            }
        }
        catch (BadLocationException ex) {
            System.out.println("BAD LOCATION QQQQQQQQQQQQQQQQQQQQ");
        }
    }
    public void enterMessage(String user){
        dialogText = dialogText + "\n" +"( " + user +  " )"+" enters this room";
        dialogTextPane.setText(dialogText);
    };
    public void leaveMessage(String user){
        dialogText = dialogText + "\n" + user + " leave this room";
        dialogTextPane.setText(dialogText);
    }
    // set original user list from client
    
    // when other user enter/leave
    public void addUser(String user){
        /*
        userList.add(user);
        userListPanel.setListData(userList);    
        */
    }
    public void deleteUser(String user){
        /*
        userList.remove(user);
        userListPanel.setListData(userList);
        client.userList.remove(user);
        sendToCombo.removeItem(user);
        * */
    }
   
    public void updateUserList(Vector<String> updateList)
    {
        userList=updateList;
        userListPanel.setListData(userList);
        sendToCombo.removeAllItems();
        sendToCombo.addItem("To All");
        for(int i = 0; i < userList.size();++i){
            if(!userList.get(i).equals(client.username))
                sendToCombo.addItem(userList.get(i));
        }
    }
    public void updateUser(Vector<String> userlist){
        userList=userlist;
        userListPanel.setListData(userList);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cryButton;
    private javax.swing.JTextPane dialogTextPane;
    private javax.swing.JTextPane inputTextPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox sendToCombo;
    private javax.swing.JList userListPanel;
    // End of variables declaration//GEN-END:variables
}
